### PR TITLE
Lints tests too

### PR DESCRIPTION
**Pull request by hrls**

### CODE REVIEW

**Comment by ales-tsurko** [comment]
probably we should consider `--all-features` as well.

**Comment by hrls** [comment]
I got an error in the frontier sources when running with `--all-features`.

**Comment by hrls** [comment]
Tracking issue https://github.com/Atleta-network/atleta/issues/100

**Comment by ales-tsurko** [comment]
> I got an error in the frontier sources when running with `--all-features`.

--no-deps?

**Comment by hrls** [comment]
Yep, no deps.
I mean for some combination of features node and runtime doesn't compiles at all.

**Comment by ales-tsurko** [comment]
> Yep, no deps. I mean for some combination of features node and runtime doesn't compiles at all.

It’s ok until it on our side, but if it shows issues to some 3rdparty code even with —no-deps flag, that’s odd.

**Comment by hrls** [comment]
What is especially interesting is that both of failed packages are checked successfully when run clippy with `--all-features` from their sources repos.
I'll add failed pipeline in [this issue](https://github.com/Atleta-network/atleta/issues/100) just for shared logs to investigate.

**Review by ales-tsurko — APPROVED** [review]

**Pull request merged**
