### PR TITLE
Deny missing docs

### PR DESCRIPTION
**Pull request by hrls**

### CODE REVIEW

**Comment by hrls** [comment]
https://github.com/Atleta-network/atleta/pull/89#discussion_r1633844250

There are no other rules that work the same way as failed pipeline. 😈

**Comment by ales-tsurko** [comment]
Maybe we should enable it as a warning in the Cargo.toml lint’s section instead?

**Comment by hrls** [comment]
Unfortunately we have error in [sdk source](https://github.com/paritytech/polkadot-sdk/blob/a51b5dd3dd7d00b0c0ae5bdd28650eb13f0ae70c/substrate/utils/wasm-builder/src/prerequisites.rs#L105) for _runtime_ package check.
There is dummy crate created during the build phase, but somehow included in the clippy targets list.
So as is workaround is to relax `missing_docs` check for _node_ and _runtime_ packages for now.

**Comment by hrls** [comment]
> Maybe we should enable it as a warning in the Cargo.toml lint’s section instead?

`Cargo.toml` `lints` section works only per package. We can add `lints` section for existing packages tomls, but it will be missed _someway_ for new ones.
IMO `missing_docs` warning is hard to use in dev-mode. We always want use as simple as `cargo clippy` without extra mess like `-- -A missing_docs` when typing.

```
Caused by:
  failed to parse manifest at `/Users/hrls/src/atleta/Cargo.toml`

Caused by:
  this virtual manifest specifies a `lints` section, which is not allowed
```

**Comment by ales-tsurko** [comment]
sorry, accidentaly edited your last comment


well, it's about personal preferences. for my own project's I always enable warn missing docs and clippy all lints and ok with the warnings 😄 but it seems like we don't have other options here rather then doing it in CI.

these warnings are especially useful when you have configured your editor with inline alerts

**Review by ales-tsurko — APPROVED** [review]

**Comment by hrls** [comment]
I'll check if this can be configured via `clippy.toml`.
`missing_docs` is `cargo check` lint, but maybe it will works.

**Pull request merged**
